name       : libbluray
version    : 0.7.0
release    : 2
source     :
    - ftp://ftp.videolan.org/pub/videolan/libbluray/0.7.0/libbluray-0.7.0.tar.bz2 : f79beb9fbb24117cbb1264c919e686ae9e6349c0ad08b48c4b6233b2887eb68d
license    : LGPL-2.1
summary    : libbluray is an open-source library designed for Blu-Ray Discs playback for media players, like VLC or MPlayer.
description: |
    libbluray is an open-source library designed for Blu-Ray Discs playback for media players, like VLC or MPlayer.
builddeps  :
    - pkgconfig(libxml-2.0)
    - pkgconfig(freetype2)
    - pkgconfig(fontconfig)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
