name       : libbluray
version    : 1.1.2
release    : 10
source     :
    - https://download.videolan.org/pub/videolan/libbluray/1.1.2/libbluray-1.1.2.tar.bz2 : a3dd452239b100dc9da0d01b30e1692693e2a332a7d29917bf84bb10ea7c0b42
license    : LGPL-2.1-or-later
component  : multimedia.codecs
summary    : libbluray is an open-source library designed for Blu-Ray Discs playback for media players, like VLC or MPlayer
description: |
    libbluray is an open-source library designed for Blu-Ray Discs playback for media players, like VLC or MPlayer.
builddeps  :
    - pkgconfig(libxml-2.0)
    - pkgconfig(fontconfig)
    - apache-ant
setup      : |
    %configure --disable-static --enable-udf
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
