name       : libbluray
version    : 1.3.1
release    : 11
source     :
    - https://download.videolan.org/pub/videolan/libbluray/1.3.1/libbluray-1.3.1.tar.bz2 : c24b0f41c5b737bbb65c544fe63495637a771c10a519dfc802e769f112b43b75
homepage   : https://www.videolan.org/developers/libbluray.html
license    : LGPL-2.1-or-later
component  : multimedia.codecs
summary    : Library for Blu-Ray disc playback
description: |
    libbluray is an open-source library designed for Blu-Ray Discs playback for media players, like VLC or MPlayer.
builddeps  :
    - pkgconfig(libxml-2.0)
    - pkgconfig(fontconfig)
    - apache-ant
environment: |
    export JAVA_HOME=/usr/lib64/openjdk-11
setup      : |
    %configure --disable-static --enable-udf
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
