name       : libbluray
version    : 1.0.2
release    : 7
source     :
    - https://download.videolan.org/pub/videolan/libbluray/1.0.2/libbluray-1.0.2.tar.bz2 : 6d9e7c4e416f664c330d9fa5a05ad79a3fb39b95adfc3fd6910cbed503b7aeff
license    : LGPL-2.1
component  : multimedia.codecs
summary    : libbluray is an open-source library designed for Blu-Ray Discs playback for media players, like VLC or MPlayer
description: |
    libbluray is an open-source library designed for Blu-Ray Discs playback for media players, like VLC or MPlayer.
builddeps  :
    - pkgconfig(libxml-2.0)
    - pkgconfig(fontconfig)
    - apache-ant
setup      : |
    %configure --disable-static --enable-udf
build      : |
    %make
install    : |
    %make_install

