name       : libbluray
version    : 1.1.1
release    : 9
source     :
    - https://download.videolan.org/pub/videolan/libbluray/1.1.1/libbluray-1.1.1.tar.bz2 : 106478a17c8bcac8c7b4174e7432b2bad5a1e6dd2926c4224791fd4669472338
license    : LGPL-2.1-or-later
component  : multimedia.codecs
summary    : libbluray is an open-source library designed for Blu-Ray Discs playback for media players, like VLC or MPlayer
description: |
    libbluray is an open-source library designed for Blu-Ray Discs playback for media players, like VLC or MPlayer.
builddeps  :
    - pkgconfig(libxml-2.0)
    - pkgconfig(fontconfig)
    - apache-ant
setup      : |
    %configure --disable-static --enable-udf
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
