name       : libbluray
version    : 1.3.4
release    : 13
source     :
    - https://download.videolan.org/pub/videolan/libbluray/1.3.4/libbluray-1.3.4.tar.bz2 : 478ffd68a0f5dde8ef6ca989b7f035b5a0a22c599142e5cd3ff7b03bbebe5f2b
homepage   : https://www.videolan.org/developers/libbluray.html
license    : LGPL-2.1-or-later
component  : multimedia.codecs
summary    : Library for Blu-Ray disc playback
description: |
    libbluray is an open-source library designed for Blu-Ray Discs playback for media players, like VLC or MPlayer.
builddeps  :
    - pkgconfig(libxml-2.0)
    - pkgconfig(fontconfig)
    - apache-ant
environment: |
    export JAVA_HOME=/usr/lib64/openjdk-11
setup      : |
    %configure --disable-static --enable-udf
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
