name       : libbluray
version    : 1.1.0
release    : 8
source     :
    - https://download.videolan.org/pub/videolan/libbluray/1.1.0/libbluray-1.1.0.tar.bz2 : e6a600d26ad3453a168dbb144f041134e954b541b44a9a5aa213d1c7d8c3fe83
license    : LGPL-2.1-or-later
component  : multimedia.codecs
summary    : libbluray is an open-source library designed for Blu-Ray Discs playback for media players, like VLC or MPlayer
description: |
    libbluray is an open-source library designed for Blu-Ray Discs playback for media players, like VLC or MPlayer.
builddeps  :
    - pkgconfig(libxml-2.0)
    - pkgconfig(fontconfig)
    - apache-ant
setup      : |
    %configure --disable-static --enable-udf
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
