name       : libbluray
version    : 1.0.0
release    : 5
source     :
    - ftp://ftp.videolan.org/pub/videolan/libbluray/1.0.0/libbluray-1.0.0.tar.bz2 : f7e3add335c7bbef45824fcd2249a9bf293868598c13f8479352c44ec95374cc
license    : LGPL-2.1
summary    : libbluray is an open-source library designed for Blu-Ray Discs playback for media players, like VLC or MPlayer.
component  : multimedia.codecs
description: |
    libbluray is an open-source library designed for Blu-Ray Discs playback for media players, like VLC or MPlayer.
builddeps  :
    - pkgconfig(libxml-2.0)
    - pkgconfig(freetype2)
    - pkgconfig(fontconfig)
    - apache-ant
setup      : |
    %configure --disable-static --enable-udf
build      : |
    %make
install    : |
    %make_install
