name       : libbluray
version    : 0.9.2
release    : 3
source     :
    - ftp://ftp.videolan.org/pub/videolan/libbluray/0.9.2/libbluray-0.9.2.tar.bz2 : efc994f42d2bce6af2ce69d05ba89dbbd88bcec7aca065de094fb3a7880ce7ea
license    : LGPL-2.1
summary    : libbluray is an open-source library designed for Blu-Ray Discs playback for media players, like VLC or MPlayer.
description: |
    libbluray is an open-source library designed for Blu-Ray Discs playback for media players, like VLC or MPlayer.
builddeps  :
    - pkgconfig(libxml-2.0)
    - pkgconfig(freetype2)
    - pkgconfig(fontconfig)
setup      : |
    %configure --disable-static --disable-bdjava
build      : |
    %make
install    : |
    %make_install
